---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus3-google
  labels:
    app: nexus3-google
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus3-google
  template:
    metadata:
      labels:
        app: nexus3-google
    spec:
      containers:
      - name: nexus3-google
        image: gcr.io/aliz-hw-wfatimah/nexus3-google:latest
        ports:
        - containerPort: 80
